### ISSUE TITLE
Ascenseur vertical & précisions sur l'interface de test

### ISSUE THREAD

**Issue by SebCanet** [ClementGre/HackCable#1]
Bonjour,
les boutons n'apparaissent pas, on ne peut pas redimensionner à la volée. Il manquerait une poignée pour faire glisser les colonnes. Rien à voir mais dans Chrome l'ascenseur vertical est énorme alors qu'il n'y a plus rien dessous.
Merci !!!

**Comment by ClementGre** [comment]
Bonjour,
Tout ce qui constitue le panneau de gauche, le header et le footer font partis de l'interface de test (dossier web). Le système de redimentionnement de l'interface "HackCable" (div #hackcable) devra être codé du côté de l'utilisateur de la bibliothèque (tel que je l'ai prévu actuellement. Le système de sauvegarde des branchements devra aussi être gérés par le développeu utilisant la bibliothèque (méthode getEditorData et loadEditorData il me semble)). Le problème de la barre des boutons qui ne se "wrap" pas a été réglé (mais je n'ai pas encore compilé ce code). Pour ce qui est de l'ascenseur vertical, je vais m'occuper de ça, je ne me suis pas encore occupé des détails de l'interface.

Merci à toi !

**Comment by SebCanet** [comment]
Excellent, t'as déjà anticipé plein de trucs, bravo.
